version: '3'

services:
  nginx_anime:
    image: nginx:stable-alpine
    container_name: nginx_anime
    ports:
      - "82:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_anime
      - mysql_anime
    networks:
      - laravel

  mysql_anime:
    image: mysql:5.7.22
    container_name: mysql_anime
    restart: unless-stopped
    tty: true
    volumes:
      - /home/dix/DB/mysql_data2:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: ajadam
      MYSQL_ROOT_PASSWORD: ajadam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php_anime:
    container_name: php_anime
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.222.1 remote_enable=1 remote_connect_back=0 idekey=PHPSTORM"
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - mysql_anime
    networks:
      - laravel

  node:
    image: node
    container_name: node
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

#Volumes
volumes:
  dbdir:
    driver: local
